### ISSUE TITLE
Thank you for DTE Energy Bridge integration!

### ISSUE THREAD

**Issue by dualtronic** [terhorst/dte_smartthings#1]
Thank you for digging this out and publishing this Smartthings device handler.  I've been looking for this forever.  Where did you find the documentation for it?  

Question: Is there any way to trigger polling more frequently, or have it trigger at different power levels?  

Thanks again!
Joe

**Comment by terhorst** [comment]
I pieced it together from a few forum and blog posts. Polling is controlled
by the hub and as far as I know there is no way to control the frequency.
You could use the schedule() or runEveryXMinutes() functions to cause a
refresh fixed intervals. On my hub poll() is called about once a minute
which seems adequate.

**Comment by pjacobs4** [comment]
Are there other http endpoints on the energy bridge that you are aware of?  I was hoping there would be daily usage as well.

**Comment by terhorst** [comment]
This is the only one I'm aware of. In order to calculate usage over time
and other interesting stats I log these measurements to influxdb and then
run custom queries.
